### ISSUE TITLE
Lost changes due confusing client error behaviour

### ISSUE THREAD

**Issue by CTalvio** [buttercup/buttercup-desktop#1024]
When editing documents, it is possible to trigger errors that will then cause all subsequent changes to fail to save.

Steps to reproduce:

1. Edit any document or create a new entry.
2. Add a custom field, but do not name it.
3. Save the entry.
4. You will get an error. But the entry will still be added to the documents list.

At this point, the client has broken. It will accept new entries, edits, and appear to function normally (aside from the absence of the notification that normally appears for each successfully saved edit/entry).

But nothing is being saved. Only manually triggering a reload will restore proper functionality. And any changes made after the error, will be lost.

Errors should not cause the clients functionality to break like this. Instead it should refuse to attempt to save if a field is invalid, or automatically perform a refresh after an error, or similar graceful error state.

**Comment by perry-mitchell** [comment]
@CTalvio Thanks for reporting this. For now I've updated the form to disable the Save button until all entry property names are entered. Leaving a field empty will disable the save button, preventing this issue from occurring.

The actual failure was an encoding one, with the underlying vault format. It wasn't able to write an empty property name - it should have thrown an error before this, but this was the simplest solution I could think of.

Fixed in 2.4.0
