### ISSUE TITLE
WebDAV Error

### ISSUE THREAD

**Issue by oopo0** [buttercup/buttercup-desktop#1026]
Hi: 
    I got error when use WebDAV in https://www.jianguoyun.com, like this:

Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: Request failed with status code 404
![图片](https://user-images.githubusercontent.com/67009994/117558075-37aed400-b0ac-11eb-83f8-33b89d0396bb.png)

Thank you!

**Comment by perry-mitchell** [comment]
404 means that the webdav service doesn't think your vault is there, at the requested location. I'd need more information, like network requests, to know as to where the issue is.

As WebDAV is working on other services I'll assume either an error not related to Buttercup or some kind of weird output from your WebDAV provider. I'll close for now - but if you come across any network requests that could help debug this, and they point to Buttercup being at fault, I'll reopen this issue.
