### ISSUE TITLE
[UI] Vault switcher

### ISSUE THREAD

**Issue by nickbe** [buttercup/buttercup-desktop#1029]
I'm missing some selector to quickly select a different vault like in Buttercup 1. Did I miss something important here?
The Interface is also confusing when adding a new vault. After adding I still find myself viewing the last vault.

I have 7 vaults right now and I'm constantly selecting among them. The colored icons for each vault on the left bar were really useful. Instead of one click to select another vault I need to step through the whole configuration with 6 clicks now 😞

**Comment by pakaoraki** [comment]
I just updated today from 1.20.5 to 2.40 on Linux, and I feel the same. It's not possible to switch vault from left panel anymore like it was before, and this is a bit confusing. On the main screen, there is only one vault to select, you need to clic "Configure vault" to select a different one. This is really painful and not intuitive as you need to do multiple "clic".

This is just a constructive feedback on the interface, the goal is not to complain but to improve the software. I am using Buttercup since a while now and I really appreciate your work.

**Comment by perry-mitchell** [comment]
We feel the same. Having some kind of UI-based approach to change vaults would be handy.. but we need to pick something that makes sense. Having the sidebar visible all the time for changing vaults doesn't make sense for _everyone_ as most people use just a single vault. I myself use 2, and several more for testing, so I feel the pain when it comes to changing them.

#1009 will help slightly as it'll introduce keyboard shortcuts for changing vaults. I'll keep this issue as the UI-option.

Sorry for the inconvenience.. Removing this feature entirely was an oversight and we'll definitely add something back to fill the gap.
