### ISSUE TITLE
Did buttercup undergo an independent security audit?

### ISSUE THREAD

**Issue by danielniccoli** [buttercup/buttercup-desktop#1076]
Did buttercup undergo an independent security audit?

[KeePass has undergone several security audits.](https://keepass.info/ratings.html) [Bitwarden did one in 2020.](https://bitwarden.com/blog/post/bitwarden-network-security-assessment-2020/)

It would be great to know what buttercup has in that regard.

**Comment by perry-mitchell** [comment]
Security audits cost money, unless someone donates their time and expertise. Being OSS with little in the way of income I haven’t explored this opportunity.

If you know of anyone that would do this for close to free I’d be interested in being connected. Otherwise I’m afraid it’s not something we can afford.
