### ISSUE TITLE
Do you know the universal package technology for linux flatpak ?

### ISSUE THREAD

**Issue by victorffrock** [buttercup/buttercup-desktop#1110]
The proposal is the same as the appimage. Provide cross-dristro applications only with slightly different operation. It is better to develop and to distribute even though you have the option of having your own repository there are repositories like flathub for example.

If you are interested in taking a look, this is the project page.
https://docs.flatpak.org/en/latest/index.html

**Comment by perry-mitchell** [comment]
We use Electron builder to bundle our application - It doesn't support flatpak, so unfortunately we won't be either.

We chose appimage because:
 * It's widely supported, without additional dependencies
 * It's easily updateable
 * It's supported by electron builder

I don't see any benefit to using it or snap either, when appimages just work - you don't even need to install it if you don't want.

**Comment by kra-mo** [comment]
> It doesn't support flatpak, so unfortunately we won't be either.

It does now

https://www.electron.build/configuration/flatpak.html

> I don't see any benefit to using it or snap either, when appimages just work - you don't even need to install it if you don't want.

AppImages don't universally run anymore, they are based on the outdated FUSE2 libraries, which are no longer supported and are a security concern.

Please support Flatpak as it is the most popular packaging format for applications on Linux at this time and would make installing the app much easier and more secure as it actually provides proper sandboxing. Publishing on [Flathub](https://flathub.org) would also help with the discoverability of the application.

**Comment by perry-mitchell** [comment]
See #1196 - isn't possible for us yet.
