### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Moilleadoir** [buttercup/buttercup-desktop#1113]
This project desperately needs some documentation. Or even a user forum.

I thought this might be a solution to trouble I’ve been having with the browser component of another password manager, KeepassXC, but it seems that it’s impossible to import data from it and it’s likely to be too much work to massage its exported CSV into a format Buttercup would accept. I’m left guessing though as all the documentation says is that you ‘can’ import from some formats.

I’m also guessing that the browser component works in a completely different way since, although there is an authorisation from the program, actually trying to add an entry from the browser fails...

```Failed saving credentials
Failed adding new entry: Failed writing remote file: /home/<redacted>.bcup
```

[not a remote file BTW]

Is this because it’s in use by the main program?  So, do I even need the main program or is its functionality included in the browser add-on?  I was surprised that I had to tell the browser add-on about the location of the database at all. It would be a lot easier to figure out why this isn’t working if I had a clue about how it’s supposed to work, but the documentation I’ve seen really tells you nothing much.

**Comment by perry-mitchell** [comment]
> Or even a user forum

We have Keybase, and Reddit.. but it's up the community to start using those..

> it’s impossible to import data from it

Buttercup supports KeePass XML format, so export to that. If your Keepass program doesn't support it I'd say that's a problem with the application. We stopped supporting KDBX because of their low-level binary requirements.

> [not a remote file BTW]

From the perspective of the extension -> desktop app, it is.. though I agree it could be described better than this.

What you describe afterwards is interaction between the browser extension and the desktop app. The local file support for the extension requires the desktop application to be open, because browser extensions cannot access the local disk.

**Comment by perry-mitchell** [comment]
In the future, please create separate issues or comment on existing ones, instead of discussing several topics in one issue.

I hear you on the documentation front - but I would need users to contribute it as well, as I'm the only one regularly developing these applications, for the moment.

**Comment by Moilleadoir** [comment]
I’d never heard of Keybase.  It’d be good to put some prominent links somewhere.

Keepass itself hasn’t been updated in quite a while, so no one should be using it. As far as I can tell a lot of the momentum is now with KeepassXC which sadly doesn’t provide XML export, only CSV.

I added details more as an example of how confusing it is to not have any documentation.  I don’t have time atm to debug it anyway, so I won’t open another issue.
