### ISSUE TITLE
Buttercup Desktop won't open on Windows 11 anymore

### ISSUE THREAD

**Issue by Claywd** [buttercup/buttercup-desktop#1135]
Not sure how to troubleshoot this anymore. I tried installing older versions but essentially buttercup won't open regardless of the application version. I click the app, I get a loading wheel and it goes away in about 1s and then nothing else happens. very unfortunate.

**Comment by Claywd** [comment]
anyone know where I can find log files for fixing this?

**Comment by perry-mitchell** [comment]
@Claywd [Here](https://github.com/buttercup/buttercup-desktop#logs).

As for Windows 11, I don't currently own it so I can't test on it. Would appreciate any help here.

**Comment by BenjamimCS** [comment]
**Heya**
I solved this by noticing something wrong at the `%USERPROFILE%\AppData\Roaming\Buttercup-nodejs\Config\desktop.config.json` so try by deleting the Buttercup-nodejs folder and check if it worked if that is the same as my case:

I was having the same trouble but on W10. In the Task Manager it's seen initializing but after a while it just close. The log shows everything going right I think, it terminates with `[INF] 06:06:19: Application ready` so that seems all worked right didn't?

## Steps
1. So snooping some files of the Buttercup in the `%USERPROFILE%\AppData\Roaming\` I've noted two Buttercup's files:  
   Buttercup and Buttercup-nodejs
1. Then, I've moved them and tried open it again and it just worked.
1. Snooping again I've noted something on the old folders, more exactly at the Buttercup-nodejs folder here `Buttercup-nodejs\Config\desktop.config.json` the .json file was empty but not the new.
	**P.S.:** Save the new desktop.config.json's content
1. With that in mind I moved the old ones again to its default location (by deleting the new ones of course) and I've got the same old thing (did not open)
1. So adding the content of the now deleted `desktop.config.json` file to the old maded it work again

So just deleted that folder or move it. That was my workaround.

I hope it helps

**Comment by xurxofp** [comment]
Thanks for the info, worked for me on Windows 11

**Comment by harddownloader** [comment]
Hi
I had a similar problem on windows 10. The program did not open after an emergency shutdown of the computer. Reinstalling it did not help, the portable version did not work either.

Solution:
Delete all Buttercup (the approximate names were - buttercup, buttercup-nodejs, buttercup-update, etc...) folders from %USERPROFILE%\AppData\Roaming\ and %USERPROFILE%\AppData\Local\

**Comment by Claywd** [comment]
@BenjamimCS you genius you. I deleted both the buttercup and buttercup-nodejs folders and its back to normal. I'd been looking for these things for a while now, I figured it had to be a system file. Super helpful.

**Comment by perry-mitchell** [comment]
If someone comes across this and can reproduce, I'd greatly appreciate logs surrounding the crash. Can't fix it if I don't know what's actually going wrong with the config.

Thanks.

**Comment by BenjamimCS** [comment]
> If someone comes across this and can reproduce, I'd greatly appreciate logs surrounding the crash. Can't fix it if I don't know what's actually going wrong with the config.
> 
> Thanks.

Fortunately it's happened again after my PC suddenly shut down. But i deleted that folder but it didn't work. That is the last log after that i think:
```
[INF] 02:07:56: Application starting
[INF] 02:07:56: Protocol already registered: buttercup
[INF] 02:07:59: Application ready
[INF] 02:08:00: Application session started: 2022-10-01T02:08:00.180Z
[INF] 02:08:00: Logs location: C:\Users\*****\AppData\Local\Buttercup-nodejs\Log\buttercup-desktop.log
[INF] 02:08:00: Config location: C:\Users\*****\AppData\Roaming\Buttercup-nodejs\Config\desktop.config.json
[INF] 02:08:00: Vault config storage location: C:\Users\idelm\AppData\Local\Buttercup-nodejs\Data\vaults.json
```

The `vaults.json` was empty :/ so i deleted it and it opened but without my vault of course :(

I created manually another `vaults.json` and it didn't open... looking the logs nothing is reported after it closes in the back just the files got renamed.

**Comment by BenjamimCS** [comment]
@perry-mitchell

**Comment by iouston** [comment]
> Hi I had a similar problem on windows 10. The program did not open after an emergency shutdown of the computer. Reinstalling it did not help, the portable version did not work either.
> 
> Solution: Delete all Buttercup (the approximate names were - buttercup, buttercup-nodejs, buttercup-update, etc...) folders from %USERPROFILE%\AppData\Roaming\ and %USERPROFILE%\AppData\Local\

Thank's a lot. I have the same problem and your answer fix it for me !
