### ISSUE TITLE
Buttercup desktop won't authenticate google drive

### ISSUE THREAD

**Issue by jsbberlin** [buttercup/buttercup-desktop#1141]
May I guide your attention to this post:
https://askubuntu.com/questions/1402828/buttercup-desktop-wont-authenticate-google-drive
This is my experience with the desktop app since years. It might have changed a little bit (I used Ubuntu and Mint). I was never capable to connect properly to google drive (this made using buttercup particular unsatisfying). So steps to reproduce are:

1. open desktop app (linux)
2. select add vault
3. select google drive
4. click Authenticate
5. authentication opens in default browser (tried both Firefox & Chrome)
6. credential input 
7. continue, a new web page opens at Buttercup.pw saying "Authenticated. You can close this window now."
8. desktop app starts prompting again at step 4

Google notice changes - local buttercup doesn't. As mentioned above: It never worked that way. My expectation for a workflow would be:

1. create local vault
2. upload it to cloud service
3. connect to remote vault and use it with browsers and apps

**Comment by JasminDreasond** [comment]
I could never in my life make the google drive authenticate works. <.>
I tried on Windows 10 and Windows 11. Failed.

**Comment by perry-mitchell** [comment]
@jsbberlin At step 7 in your list, please wait a while (10 seconds or so), and if nothing happens please open up the devtools. Are there any errors in the console?

It should open up a protocol URL that will open Buttercup desktop app, but if that's not happening it's likely your computer is not registering the protocol URL for our app. How did you install Buttercup?

**Comment by jsbberlin** [comment]
@perry-mitchell the errors are - that#s not what you are looking for I assume :)

```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. buttercup.pw:1:1

```
I had a third party cookie exception as well (google analytics). I fixed that.
What I am really wondering: It never worked on any device. Sure all of them are administrated by me, thus sort of similar. But:

- I tried it on Ubuntu Systems in recent years
- Mint 21
- windows 10&11
- Browsers typically Firefox and Chrome
- Installation typically the package provided by buttercup (deb? installed via apt, installer on windows systems)
- on Mint it's the image provided by buttercup

**Comment by perry-mitchell** [comment]
Buttercup doesn't come in deb packages anymore, as you can see on the [releases page](https://github.com/buttercup/buttercup-desktop/releases). Are you possibly using an old build?

For linux AppImage is the only format we support right now, due to it's ease of updating and ease of execution. I'd recommend also using AppImage launcher to manage installation (it's great for many AppImage based apps).

**Comment by perry-mitchell** [comment]
Closing due to lack of response. Google drive functionality has recently been updated, too, so this is possibly invalid.

**Comment by Salmonmon** [comment]
I'm having this same issue (also on multiple systems over time) using the appimage (2.26.2).

checking the firefox console gives:

`Some cookies are misusing the recommended “SameSite“ attribute 4
Some cookies are misusing the recommended “SameSite“ attribute 4
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 8
framework-2c79e2a64abdb08b.js:9:46302
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 8
framework-2c79e2a64abdb08b.js:9:46302
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 8
framework-2c79e2a64abdb08b.js:9:46302
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 8
framework-2c79e2a64abdb08b.js:9:46302
Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 8
framework-2c79e2a64abdb08b.js:9:120828
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. buttercup.pw:1:1
downloadable font: download failed (font-family: "Inconsolata" style:normal weight:400 stretch:100 src index:0): status=2152398850 source: https://fonts.gstatic.com/s/inconsolata/v32/QlddNThLqRwH-OJ1UHjlKENVzkWGVkL3GZQmAwLyya15IDhunA.woff2
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): status=2152398850 source: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
downloadable font: download failed (font-family: "Inconsolata" style:normal weight:700 stretch:100 src index:0): status=2152398850 source: https://fonts.gstatic.com/s/inconsolata/v32/QlddNThLqRwH-OJ1UHjlKENVzkWGVkL3GZQmAwLyya15IDhunA.woff2
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
downloadable font: Glyph bbox was incorrect (glyph ids 33 55 62 81 82 83 84 87 88 89 90 112 119 120 123 139 159 162 164 166 178 184 185 217 218 272 273 274 275 279 281 284 290 291 292 309 310 319 321 323 326 329 330 331 332 333 334 339 341 347 349 351 352 353 354 357 358 361 366 367 370 371 414 431 436 444 445 458 460 464 465 483 505 508 511 514 516 517 518 520 521 538 539 546 568 574 579 580 585 586 594 596 599 602 603 616 618 622 627 629 630 633 634 638 643 645 651 654 665 675 685 686 688 691) (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:2) source: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0
Partitioned cookie or storage access was provided to “https://changelog.com/podcast/325/embed?theme=night&referrer=https://buttercup.pw/?googledesktopauth&code=4/0AeaYSHAPG8UuVM6Z5-aC2uCzdc0ZDaTkzQSRw8oojOmZ76TdPcrhBS6NPmOqm13tkYfdrA&scope=email%20profile%20openid%20https://www.googleapis.com/auth/drive.file%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Prevented navigation to “buttercup://auth/google/callback?googledesktopauth&code=4/0AeaYSHAPG8UuVM6Z5-aC2uCzdc0ZDaTkzQSRw8oojOmZ76TdPcrhBS6NPmOqm13tkYfdrA&scope=email%20profile%20openid%20https://www.googleapis.com/auth/drive.file%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent” due to an unknown protocol. buttercup.pw
Missing resource in locale en-GB: devtools/client/toolbox.ftl

`

**Comment by perry-mitchell** [comment]
@Salmonmon Unfortunately those logs don't say much, and don't indicate that they're related to Google drive. We'd need more information if we're to find an issue as it seems to work otherwise. Please consider opening a new issue if you're able to find some logs that identity a cause.

**Comment by perry-mitchell** [comment]
Locking as this issue is closed.
