### ISSUE TITLE
Deleted custom fields re-appearing after a while 

### ISSUE THREAD

**Issue by taolive** [buttercup/buttercup-desktop#1190]
Deleted custom fields re-appearing after a while,
Version:
Desktop : v2.18.2
Core : v6.17.2
op:mac os

![屏幕录制2023-02-14-13 48 05-1-2](https://user-images.githubusercontent.com/1654524/218652713-c4fe76a0-1d36-46fb-bd91-40ca086a8a31.gif)

**Comment by taolive** [comment]
![屏幕录制2023-02-14-13 48 05-1-2](https://user-images.githubusercontent.com/1654524/218652644-90ed2184-9aca-49ae-a561-8f93e3ae15c7.gif)

**Comment by CaptnCodr** [comment]
Happens on Windows, too. Same versions.

**Comment by perry-mitchell** [comment]
What vault formats are you using? You can check in the preferences:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/3869469/222972184-72cd77b4-b1ff-48f8-8a5f-67d6ff55f347.png">

<img width="818" alt="image" src="https://user-images.githubusercontent.com/3869469/222972193-ebc48453-f88c-4aba-a432-5591327b3670.png">

You might try:
 1. Backing up your vault file
 2. Changing to format B if you haven't already

This would help me narrow down where the issue is.

**Comment by spr2** [comment]
I can confirm this issue for Format A vaults!

**Comment by taolive** [comment]
> I can confirm this issue for Format A vaults!

Thanks！You are right！

**Comment by taolive** [comment]
> What vault formats are you using? You can check in the preferences:
> 
> <img alt="image" width="349" src="https://user-images.githubusercontent.com/3869469/222972184-72cd77b4-b1ff-48f8-8a5f-67d6ff55f347.png">
> 
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/3869469/222972193-ebc48453-f88c-4aba-a432-5591327b3670.png">
> 
> You might try:
> 
> 1. Backing up your vault file
> 2. Changing to format B if you haven't already
> 
> This would help me narrow down where the issue is.

Thanks!
After changing to format B,The problem seems to have been solved,but it reappears occasionally!

**Comment by perry-mitchell** [comment]
I suspect that this was related to #1208.. Can you please check again with v2.20.0?

**Comment by CaptnCodr** [comment]
This fix in 2.20.0 is working for me. Great work! 🙂

**Comment by spr2** [comment]
I can confirm the bugfix for format A as well! Thank you very much!
