### ISSUE TITLE
[Google Drive] does not store changes on mac version

### ISSUE THREAD

**Issue by salehasadi** [buttercup/buttercup-desktop#1194]
Hello,
I use buttercup on multiple platforms including windows, android, linux and on none them I have no issue but mac version of app cannot store changes and always stuck like this after I try to edit or add new data.

**there is no connection issue (is checked)**

![image](https://user-images.githubusercontent.com/14921568/224344319-77feeed5-47d5-49e4-a533-625d399e1da0.png)

**Comment by WestCtr** [comment]
I also receive this issue on mac. The new entry is added to the list of entries, which implies the entry is saved.
<img width="310" alt="Buttercup Entry" src="https://user-images.githubusercontent.com/129829377/229708055-ee1eb03b-260d-42a2-bca5-adcec10b3787.png">

However after restarting buttercup the entry is gone!
<img width="310" alt="Buttercup After Start" src="https://user-images.githubusercontent.com/129829377/229708101-3470f0d3-93be-43c2-94c1-d417ac27e992.png">

This behaviour is not acceptable for a password manager, and has led to a loss of very important access for me, even a loss of funds.

**Comment by RafaMunoz** [comment]
Hello, today I have updated and I have the same problem.

![image](https://user-images.githubusercontent.com/12030658/234692595-17761427-d2c1-4faa-bea1-a0dd8ad79107.png)

**Comment by perry-mitchell** [comment]
Hi - what storage are you having troubles with? This is important to know as issues will most likely be with only 1 kind of storage.

**Comment by perry-mitchell** [comment]
Can you please try again with v2.20.0? @salehasadi

**Comment by salehasadi** [comment]
> Can you please try again with v2.20.0? @salehasadi

@perry-mitchell just checked and it's working, thanks. 
I'll close this issue according to that.

**Comment by salehasadi** [comment]
@perry-mitchell Hi, I'm reopening this because same issue is happening after update to v2.20.2 and again it's not storing information.

**Comment by Oxalin** [comment]
@salehasadi : Is this still happening? Had you tried going back to 2.20.0 at the time? If a version works and the other doesn't, bisecting commits should pinpoint to the erroneous commit.

**Comment by sascha-coenen** [comment]
For me this is still happening. In my case, when I start Buttercup fresh, then it connects to Google Drive and can push updates to it. However, if I leave the Buttercup application open, then after a while it cannot push updates to Drive anymore. The bar stays blue indefinitely. 
So this clearly seems like an issue with an expired session that cannot be renewed or re-initiated by buttercup. 
Very annoying because no menu option (reloading / force reloading) helps and one cannot determine upfront whether a session to Google Drive is already expired. So I create new entries or modify existing ones, just to find that I can neither safepoint them locally nor push them upstream. So I need to close Buttercup, loosing my edits and start fresh, hopefully remembering the sensitive data I was meaning to store. 

It would be really nice if this issue could be sorted out soon. My hint would be to have code that deals with the exception scenario of having a timed-out session and renews it and retries the action.

**Comment by Dallas62** [comment]
Hello,
I have the same issue as described, this happen on a Mac and I didn't found a version where it didn't occurs (in ~3y).
It's on DropBox provider, but maybe the issue comes from the retry mechanism or it didn't catch the network/http issue.
Regards,

**Comment by Dallas62** [comment]
Not sure to fully understand, but I don't see retry procedure like in GoogleProvide:
https://github.com/buttercup/buttercup-core/blob/5aac50d9cfab453f7df80196f7ffb031a4985f9d/source/datasources/DropboxDatasource.ts#L78
