### ISSUE TITLE
Update menu when logged-in

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#122]
The menu bar has some content that might only be relevant when logged in to an archive:

![image](https://cloud.githubusercontent.com/assets/3869469/21727522/79061b0e-d44a-11e6-80aa-2ed5ab2262ad.png)

Perhaps having the menu update and show items that are valid in the current state (logged-in/out).

**Comment by perry-mitchell** [comment]
What do you think @sallar ?

**Comment by sallar** [comment]
@perry-mitchell I'm currently doing a re-do for the "new archive" and "open archive" items, after that, we should look into this.

**Comment by sallar** [comment]
@perry-mitchell This is a bit complicated. 
Right now the menu is being built form the main process. For this, we need to move this process to the renderer process, and have a way to easily call an update. When a window comes into focus, the menu should be updated. Because two archives might be open at the same time, and one might be logged in and one not. This is not an issue for windows and linux since they should the menu for each window separately, but in Mac, the menu bar is common.

It's doable we just need to put in a bit of time.

**Comment by perry-mitchell** [comment]
> It's doable we just need to put in a bit of time.

I guess the **high effort** tag is correct then. Well perhaps we need to brainstorm this a bit. Maybe some sort of `update(mode)` function could work. We could watch for focus changes and if on mac, do it slightly differently.

**Comment by sallar** [comment]
The good thing is `BrowserWindow` emits all these events, `focus` etc. So we're in the clear. Let's get back to this later then.

**Comment by sallar** [comment]
This is fixed already :)
