### ISSUE TITLE
[feature request] Allow per-user installation

### ISSUE THREAD

**Issue by Oxalin** [buttercup/buttercup-desktop#1247]
Hi,

Since the extension will rely on the desktop application in the near future, I've been testing the desktop application in our workplace context. Users are not allowed to make per-machine installation, otherwise it must be made by a system admin. This is something new from the last couple of months, since we are tightening our user accesses across every computer provided by our organization to be inline with our confidentiality policy. Prior to this policy change, users were allowed to install and update applications that were install system wide. Also, this was not a problem with the extension, since it was/is installed per browser profile.

That being said, users are allowed to install per-user applications for permitted applications. Buttercup would be one of them.

Since we all rely on Buttercup to share a common vault (through Google Drive), it would really be usefull to have this per-user installation feature. Not a deal breaker, since our team is relatively small and it will still be manageable without this feature.

All computers provided by the office are running Windows. Some users are allowed to use their own personal computer (Windows and Mac), but they are expected to be able to install and manage their own applications according to our policies.

**Comment by perry-mitchell** [comment]
Hello! This sounds like a feature that'd be dependent on our installation system, built into Electron Builder / updater. Someone would have to research if such a feature is available there. If it isn't, it'll unfortunately be out of reach for Buttercup too.

Due to the amount of work required to maintain Buttercup, it's not feasible to switch to a more complex/custom build system that might allow such a feature, if it is indeed not possible in the current setup. I hope it is, however, as I do fundamentally agree with the premise here.

I don't have time currently to check this, but hopefully someone can check the docs at some stage to see what's possible here.

**Comment by Oxalin** [comment]
I'll have a look at it.

**Comment by Oxalin** [comment]
According to NsisOptions, there is a perMachine parameter:
"perMachine = false Boolean - Whether to show install mode installer page (choice per-machine or per-user) for assisted installer. Or whether installation always per all users (per-machine)."
https://www.electron.build/generated/nsisoptions

In the package.json file, we have:
"nsis": {
      "artifactName": "${productName}-${os}-${env.NODE_ARCHITECTURE}-${version}-installer.${ext}",
      "perMachine": true,

So, this would need to be set to "false".

I'll try to setup my computer to build Buttercup from source and test this.

**Comment by Oxalin** [comment]
By the way, ${env.NODE_ARCHITECTURE} was undefined when packaging and I had to modify it to ${arch}. Are you using a container where you define NODE_ARCHITECTURE when building? Otherwise, looking under node > process doesn't list this variable.
