### ISSUE TITLE
Doesn't open when launching

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#1260]
After #1229, the app no longer opens when launching it from the taskbar. It should, however, regardless of the minimised-at-launch setting value.

Buttercup should follow this behaviour:

| Minimised-at-launch | Launch type | Outcome |
|----------------------------|------------------|--------------|
| No                            | Startup         | Open      |
| No                            | Taskbar        | Open      |
| Yes                           | Startup         | Hidden   |
| Yes                           | Taskbar        | **Open**|

**Comment by perry-mitchell** [comment]
Note that this also affects the window re-opening after updates. It _should_ re-open after an update.

We probably need to remove the setting and just use a `--minimised` flag in the auto-start config.

**Comment by Oxalin** [comment]
The option is working exactly as I intended it to behave: Buttercup starts in the background when launching it from the taskbar or at startup if the option is enabled, because we don't have needs for the main window at this time. If we choose to, we can either open the main window (from the tray or by launching the app a second time from the taskbar or from the menu) or interact with Buttercup through its tray icon.

From what I understand of your scenarios, you expect "start application in background" to be applied only on startup launch, which is not how I had it planned. We could either add another option to separate both scenarios: auto-start in background and always start in background, with a clear description to distinguish their behavior. What do you think?

About auto-launch supporting "isHidden", it only adds an argument to be passed when calling the app. Then you have to manage it, exactly like we do with the "start application in background" option or with the "hidden" arg we already support from the command line.

**Comment by perry-mitchell** [comment]
Ok, well a simple misunderstanding then. I think the hidden on startup is more intuitive, and this creates a broken experience as nothing happens when you click the buttercup launcher. 

I'd be fine with rephrasing this setting to be more explicit, and adding the functionality so that it's only hidden on launch, not click/exec.

**Comment by Oxalin** [comment]
Is this supposed to be supported on Linux and macOS? I can test on Linux, but not macOS.

**Comment by Oxalin** [comment]
It won't work under Linux: app.[set,get]LoginItemSettings() functions are only available on macOS and Windows. That's why I had opted to use the node-auto-launch module.

**Comment by perry-mitchell** [comment]
You’re right. Though auto launch was not only lacking maintenance these days but you had to make unsupported modifications to the instance to allow passing launch arguments.

Maybe I’ll extract some of the code for Linux. Definitely a pain though 🤔

**Comment by perry-mitchell** [comment]
I migrated the functionality across just for Linux, to create a desktop file. I can see it creating the file just fine, so I'll test it on my Debian machine this morning before release.

**Comment by Oxalin** [comment]
Ok. What about macOS which has its own trickeries (and no args support from native calls)? Is there anyone who could test it?

**Comment by georglauterbach** [comment]
If there is a release, I will test it on macOS. I lack the time to build it myself, hence I can only report once a release has been published.

**Comment by perry-mitchell** [comment]
I've published it.

Yes, I can see that MacOS doesn't like my hybrid setting. It'll need some more work.
