### ISSUE TITLE
Since 2.23.0, saving preferences always close and reopen main window (not only on language modification)

### ISSUE THREAD

**Issue by Oxalin** [buttercup/buttercup-desktop#1269]
Reproduced under Windows with v2.24.4

https://github.com/buttercup/buttercup-desktop/commit/7ccab939288395ca76273bb475ebe6eea87a1872 introduced closeAndReopenMainWindow(). This should be triggered only on language modifcation so the new language is applied to the interface. 

However, as of version 2.23.0, any save of preferences calls closeAndReopenMainWindow(). onLanguageChanged() is probably being triggered for wrong events.

**Comment by perry-mitchell** [comment]
It's not a bug, and was required when originally implemented. Due to more recent features it's no longer required and could be removed.

**Comment by quintushr** [comment]
After reviewing the code, it seems that triggering the event on every configuration save might need some optimization. Instead of calling the `onLanguageChanged()` event with every preference save, could we consider triggering it only when there are actual language modifications? This might address the issue raised by Oxalin while still maintaining the necessary functionality. What are your thoughts on this approach?
