### ISSUE TITLE
Entry icons

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#16]
Support for custom entry icons

**Comment by sallar** [comment]
@perry-mitchell Are we still doing this?

**Comment by perry-mitchell** [comment]
Yes, just need to decide how..

**Comment by sallar** [comment]
@perry-mitchell we can use meta data or attributes, cant we? and just a different representation.

**Comment by perry-mitchell** [comment]
I think attributes will be more than enough.. but I'm not sure how the icon should be stored.

It comes down to the architecture of where the data is stored. If we don't store the image data inside the archive, then we have to store it in a repo which all Buttercup applications have access to (updating icons would be very hard).

We could just store the svg/base64 data in the archive as well.. that would make it more portable (but larger). This would also mean that if we update the icons later older archives won't get the updates.

**Comment by perry-mitchell** [comment]
We need to have a meeting on this.

**Comment by sallar** [comment]
I think we should just store a key, and leave the design/graphic to the client and then for showing the icons, we should have a common icon repo. This way the archive stays small and the user will always see the latest version of the icons.

**Comment by perry-mitchell** [comment]
But what if they use a newer version of the GUI than another component and the icon doesn't exist? I guess it could just show a question mark or something. 

Then we need to decide on the image format..

**Comment by sallar** [comment]
Yeah. A "default" icon in case the actual one couldnt be found. For the format i guess svg is fine, but we need to find a good icon set compatible with our license that includes most of what we want.

**Comment by perry-mitchell** [comment]
Yeah, guess svg would be good. As long as it's an MIT license..

**Comment by perry-mitchell** [comment]
Ok, so latest update.. Using [iconographer](https://github.com/buttercup/iconographer), this can be added quite easily. Storage for the icons should be on disk.

**Comment by hugo-cardenas** [comment]
Taking this!

**Comment by perry-mitchell** [comment]
Oh yeah! That’d be amazing!

Let us know how it goes. You could also PR the iconographer repo if you discover issues. You’ll need to setup file-based icon storage in the desktop app with regards to that 😊

**Comment by hugo-cardenas** [comment]
So now after reading a bit of code...

Your idea is, using Iconographer with a file-based icon storage, process entries on update/creation.
This would create image files stored in disk under some specific folder in `App support/etc` (similar as how the Redux state is stored).
Also on entry deletion, the icon would have to be removed.

On entry load, it would need to load also all the existing related images and inject them in the entry objects (as base64 strings?), which would be read and displayed by the corresponding React component.
Correct til here?

Now some concerns:
### Formats and encoding
Disclaimer: I'm not an expert here, so I had to read some stuff about encodings, still homework to do.

`Iconographer` gets just a buffer with the image data (binary) when `node-fetching`.

- Why do we need to encode/decode in the icon storage before saving/reading from disk? I understand that when loading the entries in order to pass them to React, at that point, we want to have a data-url? So at some point there is the need to convert binary -> string. But I see only this conversion, once. Not two ways back and forth.

- Where does `svg` play into this? Are the image binaries fetched **always** svg, so that when converting binary -> string, I would then make a data url like `data:image/svg+xml;base64,<here the img value foo bar>` ?

### UI
- What did you have in mind? I think the best would be to show the icon on the entry list (left of each name) and then also on the entry view/form section, somehow on top.
Something like this (I just hacked it from the DevTools)
<img width="912" alt="screen shot 2017-12-06 at 12 32 23" src="https://user-images.githubusercontent.com/1535759/33657334-abe0ad9e-da81-11e7-9525-0f2f19e30d98.png">

**Comment by hugo-cardenas** [comment]
Ok, here is now some first version of this.
Please @perry-mitchell @sallar tell me what you think.

Those specific image encoding/format concerns are still to be addressed.

I commented several things in the PR code.
