### ISSUE TITLE
Access to archives through Google Drive.

### ISSUE THREAD

**Issue by rohanthacker** [buttercup/buttercup-desktop#164]
Are there plans to support Google Drive for storing buttercup archives? I have looked through issues but was only able to find stuff related to Dropbox, OwnCloud and WebDev.

I'd also be eager to implement this functionality into buttercup.

Please excuse me if this is the wrong repo for posting this issue

**Comment by perry-mitchell** [comment]
Hi @rohanthacker - Well the right repo will be one of the following:

 * Core (only username + password required): https://github.com/buttercup-pw/buttercup-core
 * Core-web (username + password, Oauth etc.): https://github.com/buttercup-pw/buttercup-core-web

I'm not familiar with the Drive API, but I _presume_ that it requires Oauth or some kind of user acceptance. I'd guess that it should be then in core-web.

How this is implemented is by simply adding a corresponding _Datasource_ class so that serialisation works correctly.

**Comment by perry-mitchell** [comment]
@rohanthacker I'll probably close this issue, but please open one on core/core-web if you discover how Google Drive's API works. We definitely want all major cloud service providers supported!

**Comment by rohanthacker** [comment]
@perry-mitchell  Thanks for the quick response. I'll start working on this and create an issue in the right place to take it forward.

**Comment by perry-mitchell** [comment]
Thanks @rohanthacker. Please let us know if you need any help/info.

If you're looking to confirm that the integration works, it might make sense to `npm link` it to the browser extension so you can test it in a live environment. The desktop GUI might be a bit more complex if user-authorisation is required, but @sallar can help you there if you choose to try that.

**Comment by guyromb** [comment]
The feature was merged into core https://github.com/buttercup/buttercup-core/pull/248
@perry-mitchell any idea when this will be implemented for desktop?

**Comment by jsbberlin** [comment]
definitely like what you are doing. are there any plans to integrate this into the android app? that is one of the places I would pick as important (since it's hard to work around on the mobile devices). unfortunately I am not able to contribute there :-(

**Comment by perry-mitchell** [comment]
@guyromb @jsbberlin We're planning to add support for the individual apps very shortly, but in the meantime I have opened a new issue on mobile (buttercup/buttercup-mobile#148) and will reopen this one too, so we can track the progress 😊
