### ISSUE TITLE
Suggestion for Sharing / Collaborate folder Group with other people.

### ISSUE THREAD

**Issue by worldofsmarty** [buttercup/buttercup-desktop#262]
Just a suggestion for improvisation. It would have been better to have a password manager where in we can share partial of the URL's and passwords with some of our colleagues. So just wondering if that would be possible in this application..

**Comment by perry-mitchell** [comment]
Hi @worldofsmarty - This is definitely on our todo list. The core of our application **supports sharing**, but doing so will archive _files_ is not practical (merge conflicts, accessibility, encryption all make it close to impossible). We will be releasing a service this year where we'll support hosted archives, and this will support shared groups.

**Comment by ldexterldesign** [comment]
> We will be releasing a service this year [2017] where we'll support hosted archives, and this will support shared groups

What's this service's status?

Hope to hear back

Cheers

**Comment by perry-mitchell** [comment]
> What's this "service's" status - couldn't see anything hugely relevant on roadmap[r] (e.g. URLs/dates)?

It's been a crazy time since then, and we've delayed some of said service's features in favour of concentrating on some community open-source ones instead. It'll be ready very soon but no ETA right now. We're hoping for this year but just as 2017, we won't make any promises until we have the entire service running on our infrastructure.

> Related to sharing, I would also like to suggest some type of emergency access for family/friends

Emergency access is a nice idea, but I'm not sure that something in this area would help (rather than just sharing a master password, which I don't condone) and not cause security concerns at the same time. What would you propose?

**Comment by ldexterldesign** [comment]
> Emergency access is a nice idea, but I'm not sure that something in this area would help (rather than just sharing a master password, which I don't condone) and not cause security concerns at the same time. What would you propose?

Dashlane has an emergency[e] feature (one of few that actually works):

1. person #1 invites person #2 to (read) access rights and sets timeframe
2. person #2 gets notification, stating person #2 may request access
...
3. person #2 requests access
4. person #1 & person #2 get notification, stating person #2 will get access after timeframe unless person #1 declines request
5. person #2 gets access after timeframe
6. person #1 can manage access at any time

I suppose we'll need basic sharing in place before enhancing it for this [emergency, time based] use case but if you feel otherwise, and it's different enough scope, then happy to create a new issue.

The basic use case is in the instance that person #1 is unconscious in a coma for >1 month their financials have been entrusted to person #2 to request so they can pay person #1's bills
 
If you have any issues (e.g. questions/queries) then happy to help

Cheers

[d] https://support.dashlane.com/hc/en-us/articles/202625012-What-is-the-Emergency-feature-and-how-to-use-it-

**Comment by perry-mitchell** [comment]
@ldexterldesign Having such control as you suggest requires a **service**, which we're providing in the near future as a part of our business model for Buttercup. Buttercup's range of free functionality works by hosting the vault file on storage mediums, so there's no overhead for managing shared access besides the master password and the hosted directory itself.

For sharing to work outside of our hosted plans, a lock file of some description would need to be implemented to prevent conflicts while writing updates. That or the auto-consumption of conflict files as they're detected.

**Comment by ldexterldesign** [comment]
> Having such control as you suggest requires a service

Thought so but interesting insight[i] into how this could be achieved without (I assume centralised) service

Good luck with the service and please consider (emergency) sharing when you get there - that would be a feature worth paying for IMO

Cheers

i: https://en.wikipedia.org/wiki/File_locking

**Comment by perry-mitchell** [comment]
This will be handled by our hosted service, which is due soon. Will close this as it's not currently applicable to the self-hosted options.
