### ISSUE TITLE
503 error when adding credentials or archive

### ISSUE THREAD

**Issue by morojgovany** [buttercup/buttercup-desktop#277]
Hi ! I just love your app but I can't add new credentials automatically :
When I type credentials for the first time, buttercup ask me if I would save new credentials, but I just can't add it from the web browser without a 503 error

![buttercuperror](https://cloud.githubusercontent.com/assets/24272862/26764484/e93f42f0-4967-11e7-89f1-c72bf19311cf.png)

I had the same problem to add the archive from my webdav, I retried several times before making it work successfully.
![archive_buttercup](https://cloud.githubusercontent.com/assets/24272862/26764608/0375f806-496a-11e7-9834-549f1717e2c4.png)

But if I add my credentials from the desktop app, it works :

![works](https://cloud.githubusercontent.com/assets/24272862/26764509/3d3476be-4968-11e7-8607-e9655fad7ba4.png)

![buttercup2](https://cloud.githubusercontent.com/assets/24272862/26764463/a6667976-4967-11e7-888b-f56d618b974f.png)

Am I missing something ? Or is it an issue from my webdav provider ?
thanks !

Cloud host for webdav : https://indie.host/
OS : Debian GNU/Linux 8.8 (jessie)
Browser : Vivaldi 1.9.818.50 / Chrome 58.0.329.110

**Comment by perry-mitchell** [comment]
Hi @morojgovany - Thanks for creating an issue.

When using the desktop app, did you connect to your provider using WebDAV as well? Also, does your password contain special characters? If it does then there's an ongoing issue in the browser extension project which should hopefully be solved soon.

If this is an issue with just the extension we should move the issue there :)

**Comment by morojgovany** [comment]
Hi ! My desktop app is well connected to my provider via webdav. 
Effectively my password actually includes several special characters so I think you pointed out the right issue ! 
Thanks for your answer and your app ! :+1:

**Comment by perry-mitchell** [comment]
> Thanks for your answer and your app ! :+1:

Thanks a lot!

> which password is problematic ? The webdav provider's or the masterpass for archive ?

The webdav provider. In the current webdav module in the browser extension (the one in the desktop app is newer), URLs are formatted as so: `https://webdavUsername:webdavPassword@myprovider.com/some/webdav/path`. This is completely valid, but ugly and has the largest downside of all - No special characters will work because it's actually a **URL**. If your password were letters and numbers you'd have no problem, but this is of course impractical and stupid so we just need to update the webdav module (easier said than done) and this problem should go away.

Thanks for posting! I'll leave this open until it's solved.

**Comment by perry-mitchell** [comment]
We're using a new webdav library in this project, so for the desktop application this issue with the password and special characters should be solved.
