### ISSUE TITLE
Support freedesktop secret storage API

### ISSUE THREAD

**Issue by bagage** [buttercup/buttercup-desktop#280]
I am not sure how many applications use it as of today, but it would be really awesome to have [freedesktop secret storage](https://specifications.freedesktop.org/secret-service/) support in buttercup.
Any plan in supporting it? I personally would use it for [Eolie, a new modern browser](https://github.com/gnumdk/eolie). 
But I believe other desktop applications use it (for instance [email client Geary?](https://wiki.gnome.org/Apps/Geary)).

**Comment by perry-mitchell** [comment]
Thanks for posting @bagage - This really depends on two things:

 * Community interest and support (PRs & maintenance)
 * Testability

First and foremost we'd need an easy way to test it so that would remain stable between releases. After that, someone would need to implement a **Datasource** in the core library. Once that's done and released, we'd need to add explorers to the browser extension and this desktop application. 

If someone's willing to research it and put in the effort, we could definitely consider adding it. It would have to be for more than 1 person of course, so we'd need to know what the usage would be like.

**Comment by perry-mitchell** [comment]
I'm going to close this for now, as we definitely don't have the bandwidth to add this currently. We would definitely consider a PR to add this to the desktop application and maybe the core library. Further cloud storage integrations can be tracked on our [roadmap](https://github.com/buttercup/roadmap/blob/master/roadmap/CLOUD_SERVICES.md).
