### ISSUE TITLE
Add localisation support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#285]
Add support for localisations.

**Comment by ph1p** [comment]
Hi there! I've written a solution with react-intl. It's not fully complete, but it's an idea how it can be done.
After I pushed my code, I've seen that an i18next branch exists *facepalm*, but this small session helped me to get into the code and I discovered some tricky parts like main folder translation, system files translations in renderer folder, handling dynamic content and the need of restarting the application after changing the lang(e. g. main menu). I've added example codes for all of these.

Source: https://github.com/ph1p/buttercup-desktop/commits/master
- I added an i18n folder with language files in json format.
- Every word has its own id. 
  - e. g.: *components.file-manager.index.open_in_buttercup* (folder.folder.file.word) this was my first idea, but I'm sure there is a better solution.
- I also added a react-intl wrapper to file-manager.js and index.js. This wrapper is imported from an configuration file located at the i18n folder.

Have a nice weekend!

**Comment by sallar** [comment]
Hi @ph1p. Yes we started working on i18n a while ago but haven't had a chance to continue because of other priorities. Is it possible for you to send a PR to at least discuss your code? I can't promise merging it yet but it would be nice if we had a discussion over a PR. 
Thanks for putting in the time to contribute to Buttercup :) Have a nice weekend.

**Comment by ph1p** [comment]
Hey @sallar! Sure :) 
I was not quite sure, because of the existing branch. 
I've created a pull request. First one I've ever made on an public repo 🎉
