### ISSUE TITLE
Unable to connect to webdav at alwaysdata

### ISSUE THREAD

**Issue by CircleCode** [buttercup/buttercup-desktop#303]
I can successfully connect with cadaver, but buttercup cannot: `Connection to https://webdav-username.alwaysdata.net/ failed. Please check your credentials and try again.` (I triple checked my credentials)

Note: for testing purpose, alwaysdata offers free accounts (see https://www.alwaysdata.com/en/pricing/ -> free plan)

**Comment by sallar** [comment]
@CircleCode Thanks. I will check this out using their free acount.

**Comment by perry-mitchell** [comment]
Ok, to follow up here..

It appears as though the issue has to do with the native `window.fetch` call we were doing [here](https://github.com/perry-mitchell/webdav-client/blob/v0.9.0/source/adapter/request.js#L5). We've since removed that call and are updating our software, which should hopefully fix the issue.

**Comment by sallar** [comment]
@CircleCode This issue has been fixed in 0.18.0. Please update :) Thanks.

**Comment by CircleCode** [comment]
I can confirm this has been solved by updating, thanks 👍
