### ISSUE TITLE
It does not work on windows 32 bit.

### ISSUE THREAD

**Issue by lalitsom** [buttercup/buttercup-desktop#364]
I have downloaded the setup (0.21.4) from your website and it gave me an error 64 bit required.
If it does not works on 32 bit, then you should mention that on site.
I know it is not a big thing but it could save some time for people still using 32 bit.

**Comment by sallar** [comment]
@lalitsom Thanks. We should do a better job mentioning that we don't support 32bit Windows systems. I understand that there are still users using the 32bit version of Windows, but supporting that will require some additional work from our part and we haven't seen enough users using this version to justify the work. But if there's enough demand, we would consider that perhaps? @perry-mitchell

**Comment by perry-mitchell** [comment]
At this stage it's quite a bit of work to support 32 bit windows, for a number of reasons:

 1. Not straightforward (even not possible?) with our build system
 2. Not easily tested (we don't have windows licenses and are limited to where we can test our windows builds - 32bit is very rare these days)

So unless we have some easier way to test the 32bit builds (perhaps Azure?), and someone wants to contribute to the build system so that it supports 32bit builds in a clean manner, I don't see us having 32bit support in the near future if at all, sorry.

This might sound a tad harsh and I apologise, but in my opinion there should be little to no reason to be using a 32 bit build of windows - Obviously embedded systems and the like are a different matter, but with only 2 full-time devs we can't support every version of every platform.

**Comment by perry-mitchell** [comment]
Upon having a more detailed discussion with @sallar regarding this, we will **try** to enable the 32bit build flag. Hopefully we'll end up with out-of-the-box 32bit support. I would still consider marking it as a currently unsupported version in the readme, but of course if demand picks up then who knows, we may add a proper build+test pipeline for it.

Thanks for taking the time to drop us an issue - hopefully we can add support for your platform.

**Comment by sallar** [comment]
@lalitsom Here's Windows 32bit support: https://github.com/buttercup/buttercup-desktop/releases/download/v0.22.0/buttercup-desktop-setup-0.22.0.exe
Please download it and let us know how it goes :)

**Comment by lalitsom** [comment]
@sallar Thanks for the quick support. It works now. 👍
