### ISSUE TITLE
Locales: Nest some items

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#406]
Currently the locales are mostly hyphenated. Some ones, like **errors**, could be prefixed with such a namespace: `error.some-item`, for example.

Change some of the obvious locale property names to namespaced options.

**Comment by ph1p** [comment]
I thought about nearly the same type of naming, this is why I added `-error`.

**Some proposals + examples:**
- archive - open-archive-file **to** archive.open-file
- entry - add-entry **to** entry.add
- group - new-group **to** group.new
- error - archive-not-found-error **to** error.archive-not-found
- info - archive-saved-loading-info **to** info.archive-saved-loading

**Comment by perry-mitchell** [comment]
I think that you've got the idea, besides maybe _info_. In my opinion it'd be best to sort by logical area of the app. Errors are their own thing (all messages), but the other areas of the app are very easily distinguishable:

 * Archive(s)
 * Groups
 * Entries
 * Importing
 * Menus
   * Context menu on archives
   * Window menu
   * Context menu on entries etc.
 * Connections (webdav/dropbox etc.)
 * Menu actions (hide, reveal etc.)
 * User actions (Confirm, Cancel, Yes, No etc.)

**Comment by hugo-cardenas** [comment]
Hi guys!
Finally I get to give a hand with Buttercup. I thought to pick this as a first simple and boring task, to get going with an easy one and find my way around the project.

**Comment by perry-mitchell** [comment]
Hey @hugo-cardenas! Welcome. That would be awesome! Let's get through that current PR and you could most definitely take this item :)

**Comment by perry-mitchell** [comment]
This is now ready @hugo-cardenas, if you get time. I guess there are already some nested errors, but I think there's a lot that could be categorised. This can obviously be a partial PR due to the large amount of items that may need changing.

**Comment by hugo-cardenas** [comment]
Hi! I created already a PR (#446) in order to discuss better the format as I change things.
I nested the items for the window menu in the English config for now.

Are you guys ok with the structure like this?

Also, I noticed there were some items used in multiple contexts (e.g. `hide`, `copy`, etc). At the moment, for those used from menu + somewhere else, I kept them duplicate, in the new menu structure, and in their original place, used somewhere else.

I believe it would be better not to reuse items in different contexts, even though they might happen to contain the same value.
If later some UI element is removed/changed, when you remove/change the locale items with it, it's nicer if you don't risk breaking other things which use the same item. 
What do you think?

**Comment by perry-mitchell** [comment]
> I believe it would be better not to reuse items in different contexts, even though they might happen to contain the same value.

> it's nicer if you don't risk breaking other things which use the same item

Thoroughly agreed!

> Are you guys ok with the structure like this?

Perhaps we should discuss that on the PR 😊
