### ISSUE TITLE
Failing builds on AppVeyor

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#419]
AppVeyor giving us no love at all:

![image](https://user-images.githubusercontent.com/3869469/32959297-dec7c2d6-cbc9-11e7-84a7-58d047630921.png)

Tests are ultra-erratic and need to be fixed somehow.

**Comment by sallar** [comment]
@perry-mitchell I guess this can be closed since #420 is merged? 
I don't see any other options other than these:

+ Remove fsevents and node-sass, which are the main fail points. But a CI system shouldn't care about these so I don't suggest doing this
+ Move to another CI system, that supports Windows, but I haven't been able to find one personally. 
+ Wait for AppVeyor to fix it, which is a bit unlikely to happen soon. 

So I say your "temporary" solution is rather permanent. lol.

**Comment by perry-mitchell** [comment]
Yeah.. Let's close it unless it occurs again. If it keeps happening I guess we need to consider moving to another CI system. I'm considering self-hosting something if it gets bad (would need to do so for iOS tests too).

**Comment by perry-mitchell** [comment]
Well.. there goes that idea. `AppVeyor.stability = null`.

**Comment by sallar** [comment]
@perry-mitchell this issue seems to be fixed since you last fixed it. closing this again!
