### ISSUE TITLE
Can't open archive in Mac and Windows

### ISSUE THREAD

**Issue by peymanslh** [buttercup/buttercup-desktop#443]
I've been using Buttercup for a few months on Mac, after launch iOS app I use that, and since last week I open my archive in Buttercup for Windows. Now I can't open my archive in Buttercup for Windows and Mac, but I do not have a problem with Buttercup for iOS.

I use Dropbox for sharing archive on Mac, Windows, and iOS.

_Error in Buttercup Mac when entering password:_

![i_f_w1nv](https://user-images.githubusercontent.com/7171098/33219252-954c5e4a-d156-11e7-9c78-9ae5b458b98a.jpg)

**Comment by perry-mitchell** [comment]
Sorry to hear that.. What happens if you save again using the iOS app (make a change)? Does it allow you to open it then on either desktop?

**Comment by peymanslh** [comment]
I created a new entry using the iOS and the problem was resolved 👍
Thanks.

**Comment by perry-mitchell** [comment]
It's possible that there was some error during writing, but I've tried and have not been able to reproduce this. Please let us know if it occurs again, and we can reopen this.

If it's a reoccurring problem, perhaps you could make a sample archive and then send it to us when it breaks.. Otherwise, thanks for posting!

**Comment by peymanslh** [comment]
Okay, sure
Thanks again
