### ISSUE TITLE
Minimum master password strength

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#449]
I think we should consider specifying a minimum set of password standards for Buttercup. Users probably adopt a password manager for a number of reasons, but one must be for a sense of security. Trusting Buttercup to securely store someones online profile is a big ask, and we owe it to the users to make some decisions on their behalf when it comes to _sane_ defaults.

Having a required password strength may prevent some users from choosing obviously-weak passwords. Some items we *may* consider:

 * Minimum password length (I'd say that this is a must)
 * Common words (filter common passwords)
 * Character sets (letters/numbers)

We shouldn't go overboard here. Of course it'll still be possible for "powerusers" to set unsafe passwords when using the core library, but some defaults may go a long way with users new to the process. Same goes for signing up to a new website.. If some online account has these requirements, why doesn't our password manager? 😊

**Comment by jgtoriginal** [comment]
@perry-mitchell I wouldn't be too hard on the master's password policy, just stick to the standards (1 uppercase, 1 lowercase, 1 special character, 1 number, 8 chars long).
However what I'd strongly suggest going for is 2FA, at least yubi key and Google 2FA. Because even if the master password is weak or get's compromised, and attacker would still need to steel your physical one time token generator (whichever it is). And this makes the attack vector way weaker.

**Comment by perry-mitchell** [comment]
Agreed @jgtoriginal, that's what I meant by not going overboard.

The 2FA thing is not related in my opinion - 2FA requires a server and an account. This is something that our upcoming service will provide, but only for people wanting a hosted account and archive. Users may still opt to use Buttercup in the current standalone fashion (remaining completely detached from any central service). I definitely agree that two factor is the way to go for a more secure platform overall.

**Comment by jgtoriginal** [comment]
You are right @perry-mitchell most of 2FA require server and account. But think it this way, authentication might be by validating at least one of the following 3:

* Something that you know
* Something that you have
* Something that you are

So without going crazy, but just a bit creative, apart from knowing your password, you can have to scan a specific QR code -for instance- that only you'd have. This is still 2FA, without one time token for sure, but always stronger than just something that you know.

The most common problem I see across different password managers is just lack of creativity, really. =)
But that's just my personal opinion, really.

**Comment by darsain** [comment]
Please no. Don't enforce how you think people should use something. Trying to prevent dumb people from shooting themselves in the foot always leads to annoying limitations for everyone else.

For example, what if someone wants to test something and create one or many databases with single letter master password so it's easy to enter 50 times in 10 minutes ([like I needed here](https://github.com/buttercup/buttercup-desktop/issues/520)).

If someone knows what they are doing and they want a weak password, let them. Otherwise it's like banning forks because someone might stab themselves with them.

**Comment by jgtoriginal** [comment]
@darsain that's a good point, and here comes the classic chicken and an egg situation between security and functionality, which is easy to solve really. In stead of enforcing you can:

* Add a warning message with a password strength meter, to let them know how strong is the password they are choosing, but without forcing them to do anything.
* Add the 2FA option for people who has bad memory for strong passwords but still want to enhance their security level.

I think we are missing the point if we enforce people, because if done right, you just offer better options and drive them through in case they want to follow you. And for those who don't want to follow your suggestions, just let them know that it's at their own risk. 

If you don't give options, then you are loosing the opportunity of offering a better solution, thus loosing valuable customer base.

**Comment by darsain** [comment]
The best warning would be to give people an estimated time it'd take the current fastest supercomputer to bruteforce the password. And a 2nd estimate of when it'll be practically bruteforceable (like below a year of computing time) if the current Moore's law trend continues.

That'll make people use strong passwords when they truly need them.

**Comment by jgtoriginal** [comment]
@darsain that's actually a brilliant idea. I've seen it here couple of days back http://random-ize.com/how-long-to-hack-pass/  UI isn't great, but that's the concept. right?

**Comment by darsain** [comment]
Yeah. With this kind of warning you've basically gamified making strong passwords, and everyone will be compelled to get the best score. I know I'd definitely make an effort to get at least the age of the universe :)

**Comment by perry-mitchell** [comment]
Good idea.. thanks @darsain, @jgtoriginal. I'll close this in favour of #531.
