### ISSUE TITLE
Duplicated password files - Version 1.2.1

### ISSUE THREAD

**Issue by pelonchasva** [buttercup/buttercup-desktop#522]
Hello guys,

I just updated to the latest version of Buttercup and when it finished and loaded again, there are a lot of password files showing up (even though I have just two), you can see it in the screenshot below:

![buttercup-issue-1 2 1](https://user-images.githubusercontent.com/4713147/36312047-33b67fbc-12fb-11e8-8e02-00762b477b5b.png)

Please take a look into this because it is a bit confusing to look at.

Thanks

**Comment by toniobido** [comment]
Hi guys, 

First thanks for your great job ! :)
I have the same problem when I'm adding a new archive and I enter a wrong password

**Comment by sallar** [comment]
@pelonchasva @toniobido what happens when you click on one of the extra items?

**Comment by perry-mitchell** [comment]
@pelonchasva @toniobido This may be due to some issue with localstorage within the app. What happens if you delete the duplicates?

I tried myself entering the wrong password, but I can't seem to reproduce the problem.

**Comment by pelonchasva** [comment]
Hi guys,

Sorry for the delay, I was out this weekend, so after checking out, I can click on any archive and it works good, maybe there is just a little bug when reading and showing the last archives.

**Comment by perry-mitchell** [comment]
No problem @pelonchasva - Did you try deleting them?

**Comment by pelonchasva** [comment]
I'm going to try and delete them, but just in case, I'm going to do a backup of my archives just in case something bad happens, I'll let you know what I found.

**Comment by pelonchasva** [comment]
So I just deleted the extra archives from the app, and it seems it is not causing any issue, certainly it is just a small bug, but I'm looking into it for those users who have a lot of archives, will be time consuming to reorganize their archives, still, it works great.

Also, does Buttercup comes with some kind of log so I can check it out and get more feedback for you guys?

Thanks

**Comment by toniobido** [comment]
Hi, 

It's happen only when i'm adding an archive from Dropbox, When I click one of the wrong archive (ex "PA" ith no Dropbox overlay) I can't unlock it, event with the right password. 
![sans titre](https://user-images.githubusercontent.com/14336821/36471345-698dcd56-16ee-11e8-8cb5-1069f3501184.png)
I can delete wrong items

**Comment by sallar** [comment]
I think the temporary solution is removing them and adding them again. I know this is not a solution but it's also unlikely for it to happen again. We changed the internals of how archive manager works, and for some reason this issue has been happening. But this change fixed some other problematic issues.. I will anyway investigate to see what's causing it, but the problem is it's hard to reproduce.

**Comment by darsain** [comment]
Related issue: Oening an archive that is already in the list by double-clicking on the `.bcup` file adds it to the list again, creating a duplicate.

Also, buttercup doesn't seem to have a single instance mode enabled. This allows multiple buttercup instances to run, possibly fighting over database access.

Practical case when this might happen: you have buttercup open, and you want to add another `.bcup` database. You double click on it and instead of it being added to the current instance (or activated when it's already in the list) you get a new buttercup window. And since both instances share the same session settings storage, there will definitely be conflicts and confusion.

OS: Windows 10

**Comment by sallar** [comment]
@darsain could you open another issue for these two problems so we can tackle them separately?

**Comment by darsain** [comment]
@sallar #543, #544
