### ISSUE TITLE
Archive Search

### ISSUE THREAD

**Issue by ph1p** [buttercup/buttercup-desktop#548]
Hi!

I'm using buttercup daily. Often I need a password very quickly and I don't want to click multiple folders to open the entry. There is no solution yet to search globally. So I've written one. I know its not perfect but what do you think?

You can open it via main menu or `cmd/ctrl + f`.

This is currently a `title` search with `findEntriesByProperty('title', '')` from buttercup-core.
It only searchs in the active archive not across all opened archives.

Icons are only placeholders, because I've not found a solution yet to get them.

![search](https://user-images.githubusercontent.com/15351728/36591395-309b5ffe-1892-11e8-957e-88ecd278d544.gif)

**Comment by sallar** [comment]
This is related to #136 and #314.
@perry-mitchell this looks like a good solution to our UI problem?

**Comment by sallar** [comment]
@ph1p can you open a PR so we can discuss there? since this is a code-related discussion and not an actual issue. then we can close this one and mention those are tasks from the PR. You can also make the search to include the other open archives as well. it's what buttercup browser extension does, so its nice to have the same experience.

**Comment by ph1p** [comment]
Ok you can close it :)  I'll sent a PR.

**Comment by perry-mitchell** [comment]
This looks amazing! I love the idea.

For me I think it'd be best to use the `EntryFinder` code in the core, as [used here in the browser extension](https://github.com/buttercup/buttercup-browser-extension/blob/master/source/background/library/archives.js#L175).
