### ISSUE TITLE
user experience

### ISSUE THREAD

**Issue by aesthicc** [buttercup/buttercup-desktop#617]
I've been using buttercup for a few weeks now and overall it's really nice but I would like to share some thoughts:

1. When I open buttercup i would just like to type in my password for my main vault instead of selecting it - a setting for this would be nice

2. When I start typing once I'm in my vault, buttercup doesn't: 
	- go to a corresponding entry in the list 
	- start the search function
It seems to me like one of these should be implemented

3. command/control + N creates a new vault instead of an entry when a vault is opened - this seems silly to me

**Comment by perry-mitchell** [comment]
Hi @aesthicc:

> When I open buttercup i would just like to type in my password for my main vault instead of selecting it - a setting for this would be nice

#124 does something like this. You can also use `Cmd+1` (or the index of the archive) to select it using the keyboard.

> go to a corresponding entry in the list

> start the search function

You can use `Cmd+F` to search.. I don't see any use in reading keystrokes adhoc. 

> command/control + N creates a new vault instead of an entry when a vault is opened - this seems silly to me

I agree on this point. From a usability perspective you're more often going to create new entries/groups and not vaults. @sallar ?

**Comment by aesthicc** [comment]
Hi @perry-mitchell 
Thank you for the information.

> You can use Cmd+F to search.. I don't see any use in reading keystrokes adhoc.

Almost every app does this though so it makes sense from a continuity perspective. If I type "b" in finder it selects the first entry that starts with that letter. It's almost surprising when this doesn't happen. Thanks for considering!

**Comment by sallar** [comment]
@aesthicc @perry-mitchell 

I like the idea about changing Cmd+N to creating a new entry instead of a new archive, since we wont be creating new archives so often. I think I'll do that soon.

About the letter capture on keyboard, I understand it would make it more "native"-looking and I would love to have it. For example like in Mac's finder or Windows explorer when you start typing in a list, the relevant item gets highlighted or scrolled into view. However we don't have enough bandwidth for that right now as there are a multitude of other issues to be fixed. I'd appreciate it if someone could add that as a PR :)

**Comment by perry-mitchell** [comment]
The problem with the keyboard capture is that it's fraught with potential issues. What happens if we don't recognise input focus properly and it thinks we're searching?

I don't think searching is so hard as to try to make it automatic when someone is typing.. it's simply not intuitive. More often then not, if someone is typing it's probably out of error, not knowing that it's a feature. IMO such a feature is unnecessary..

**Comment by perry-mitchell** [comment]
I'm going to close this issue as it's too general. The first point is already covered in another issue, and the other points are in contention. I did create #649 for the keyboard shortcut, however.
