### ISSUE TITLE
[Feature Request] Open local database in browser extension

### ISSUE THREAD

**Issue by manzing** [buttercup/buttercup-desktop#671]
Hi
I tried Buttercup and i love its GUI.
There is a missing feature that is very surprising to me.
With Firefox addon, i cannot open local buttercup database, only cloud synced database.
What if i only own one computer and / or just want a local archive for security reason ?

So, is it possible to add an option to load and use a local buttercup database in browser extension ?

Thanks for this great app, keep improve it.

**Comment by sallar** [comment]
Hi @manzing 
Accessing local file-system is not currently possible through browsers. This is due to security reasons and is a limitation enforced by the browser makers.

However we are thinking about a solution to connect the browser extension to our desktop client so you would be able to read the vaults directly from the desktop app.

**Comment by manzing** [comment]
That would be great, i hope you will be able to achieve this.
Thanks @sallar

**Comment by perry-mitchell** [comment]
The issue for this topic is here: buttercup/buttercup-browser-extension#91

I'll close this in favour of that issue.
