### ISSUE TITLE
Key-file support alongside password

### ISSUE THREAD

**Issue by mpourismaiel** [buttercup/buttercup-desktop#69]
It's not safe that all the archive is accessible by entering a pass-phrase, especially when the pass-phrase doesn't need to be strong. While by generating a key file and suggesting to keep it away from the system, the data will be more secure.

**Comment by perry-mitchell** [comment]
This requires buttercup-pw/buttercup-core#38 before the interface can be built in this project.

**Comment by perry-mitchell** [comment]
Key files are now supported in buttercup-core.

**Comment by sallar** [comment]
Perhaps a second release after the GUI rework could include keyfile support. Right @perry-mitchell?

**Comment by Aktariel** [comment]
Are there any plans to support something like YubiKey/general FIDO U2F devices? It's pretty nonstandard and [1Password provides some pretty good reasons why it's not necessary](https://blog.agilebits.com/2011/09/23/two-factor-or-not-two-factor), but it would be nifty to have support (since I carry a YubiKey anyway). Multiple keys would be great (in case one was lost. TOTP is probably infeasible (and a bad idea). Please note I'm not talking about Dropbox etc _login_ support, but rather archive decryption support.

From a core/crypto perspective, perhaps MasterPW+YubiKey response could be pass+salt for the PBKDF2 seed? Multiple keys could work similarly, but then you'd have essentially x passphrases that could unlock an archive (where X is the number of YubiKeys configured to unlock the archive: MasterPW+Key1, MasterPW+Key2, etc). Unsure if this is a good idea in practice, but I'd love to explore more/chat about possibilities.

**Comment by sallar** [comment]
@Aktariel Yes, an issue is submitted for that: #233

**Comment by Shosta** [comment]
@sallar That is a very good news that you are going to support FIDO U2F as a 2-factor authentication method.
But be careful not to realy on on Yubikeys because U2F is a standard and there are a lot of others U2F ready keys on the market.

**Comment by sallar** [comment]
@Shosta thanks. Please update the related issue with more information if possible, so we have a bit more knowledge on the matter.

**Comment by Shosta** [comment]
Hi, 

Some links on the protocol:

    https://fidoalliance.org/download/
    https://developers.yubico.com/U2F/

Happy to provide more info if needed.

**Comment by Aktariel** [comment]
#233 is what I was stating I was explcitly *not* referring to - rather than U2F support for logging into a syncing service, I was speaking about using a U2F device as a sort of physical key file along wih a password to decrypt an actual buttercup _archive._ (unless I'm misunderstanding how Buttercup uses Dropbox, which is simply as a cloud-synced folder storage of an encrypted archive file, not as a complete login solution for Buttercup)

Dashlane has some info [HERE.](https://csdashlane.zendesk.com/hc/en-us/articles/207051919-U2F-functionalities-with-Dashlane). LastPass supports U2F as well. Importantly, though, is that those are essentially logins to a _service_, not for decrypting a file. Hence my suggestion above - though I'm open to doing some more digging. 

U2F as a standard is being subsumed by the Web Authentication standard, which all major browsers will apparently support, but that's a little ways off - see eg [THIS for Chrome](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/qCJhuuZH5p0/le6l1t37AQAJ) and [THIS for Safari and general context.](https://www.mail-archive.com/webkit-dev@lists.webkit.org/msg27102.html)

More information on U2F in general [HERE,](https://sites.google.com/site/oauthgoog/gnubby) code for an iOS app to pretend to be a U2F device [HERE,](https://github.com/mastahyeti/security-key/) and a great write up (yes by Yubico) of how to use a YubiKey as an OTP device [HERE](https://www.yubico.com/why-yubico/for-individuals/password-managers/keepass/) - please note that this is not a U2F solution, but still something that would be pretty cool.

All of that ->^ aside, I imagine this is pretty low on the priority list - there's definitely lots of UI work I would thrill to see completed first (though I'm much more of a C/C++ person; this React/web stuff is pretty new to me).

**Comment by perry-mitchell** [comment]
This is definitely an interesting area of work, but it should be noted here also that our app is built on Electron and therefore Chrome - which does not support most features boasted by Yubikey. We're limited by that and are very much downstream.

If there are ways for yubikey to provide a key as text input or some other way that's not hard to implement we could look at integration already. Otherwise I'm not sure that there's much to be done here..

**Comment by aleclarson** [comment]
> ... it should be noted here also that our app is built on Electron and therefore Chrome - which does not support most features boasted by Yubikey.

Porting buttercup to [react-native-macos](https://github.com/ptmt/react-native-macos) is one option. Of course, that transition takes time and effort, but at least it's still React. If you do consider this, you might want to wait for [RN Fabric](https://github.com/react-native-community/discussions-and-proposals/issues/4) to land.

**Comment by pmyers** [comment]
Is there any update on when we might see keyfile support in the UI for accessing the Buttercup archive (in addition to the password)? Even with strong encryption it's very risky to leave a vault on a cloud platform if it only has password protection and no second factor auth mechanism. Thanks!

**Comment by perry-mitchell** [comment]
For this to continue, we'd need someone to add keyfile support to our [datasources](https://github.com/buttercup/datasources) and [credentials](https://github.com/buttercup/credentials). After this, we could begin adding it to the UI.

**Comment by perry-mitchell** [comment]
This seems out of scope and stale.. it's not getting done. U2F style key support might be added, if we get help on it, but key files will probably disappear.
