### ISSUE TITLE
Show vault details on hover

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#700]
Buttercup allows to add vaults by different hosts and so different URL to vaults exist. That's why it would be useful to get the URL hovering over the vault's icon (e.g. as tooltip). Like that:

![bildschirmfoto 2018-11-24 um 23 45 06](https://user-images.githubusercontent.com/25926588/48973614-71f29b00-f043-11e8-8c42-f4990a69835f.png)

**Comment by perry-mitchell** [comment]
I think it'd be great if a few details were shown:
 * Type
 * Source location (URL)
 * Status
 * Last opened? (Could be access timestamp)

**Comment by LukasWerfel** [comment]
Id like to try it!

**Comment by sallar** [comment]
@LukasWerfel go for it :)

**Comment by LukasWerfel** [comment]
Do you guys already have some functionality or component for hovering I can re-use?
Also, anything in particular design-wise in mind?

**Comment by rodmatos** [comment]
Since it's been 4 months since the last response and I was looking to dive into buttercup. I'd like to know if you're working on it @LukasWerfel and if not if I could take it from here. Cheers.

**Comment by perry-mitchell** [comment]
@rodmatos We'd really appreciate the help! I think, due to the lack of response, that perhaps he might not be working on it?

**Comment by julianpoemp** [comment]
Could anyone implement this little information panel, please? I think, that the effort should be low and the benefit high :)

**Comment by perry-mitchell** [comment]
Renamed to better suit what's needed: details about the vault connection. URL not applicable for all connection types, so it should be custom data - email for dropbox, url for webdav etc.

**Comment by perry-mitchell** [comment]
After thinking about this further, I've realised an issue. The problem here is that this information is **not available** when locked, as these details are **private**. We can't show them when encrypted, and this is definitely not something we're willing to budge on. Emails, URLs etc. are all personal and secure data that should always be hidden, unless the owner unlocks the vault source.

This makes me think that this feature kinda isn't possible at this stage. It would be better to, such as in the browser extension, allow the user to choose and edit the source title once added. What do you think @sallar?

**Comment by julianpoemp** [comment]
I'm closing this issue because I don't think it's relevant anymore.
