### ISSUE TITLE
Win10 Unhandled Error: spawn C:/Users/.../buttercup-desktop-setup-1.13.0.exe EACCES

### ISSUE THREAD

**Issue by mokhosh** [buttercup/buttercup-desktop#725]
Also the update dialogue borders on nagware guys.
Please add a preferences section where we can decide on these little things.

Awesome app. Really appreciate it.

**Comment by mokhosh** [comment]
> In the future please try to keep issues limited to one item, so they're easier to address. 

Will do.

> Not sure what you mean.

I  meant the app keeps reminding me of the available update which is really annoying. Either download and install it automatically (preferably just the updated parts and not the whole electron engine), or just stop asking until the next update, or give me an option to check for updates manually.

**Comment by perry-mitchell** [comment]
> download and install it automatically

This is possible, but I find this quite intrusive - We can't know reliably what type of connection the user is on for a start.

> stop asking until the next update

We don't want this right now because we want users to always be reminded when critical updates are provided. Having the ability to skip updates would require that only non-critical updates can be skipped.

> preferably just the updated parts and not the whole electron engine

Currently there's no option here that I'm aware of - our build process builds the entire project into a binary setup executable, which is what's used by the update system. We're using 3rd party components here (provided with Electron) as we're not currently investing effort in writing our own.

> an option to check for updates manually

We have the check-for-updates menu item, but I assume you just mean a manual update procedure rather than an automatic one.

I think our only option here is the critical/trivial update attributes.. so we'd need the ability to mark and detect this before we can change the behaviour.
