### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by neojp** [buttercup/buttercup-desktop#781]
I just started using it and am loving it so far. I have a few issues in general, but overall I'm really happy, thank you guys!

My biggest issue is speed when using the Desktop app with an archive of 967 entries.

Using the Desktop UI tends to lag at unlocking, rendering the app, switching folders, and even searching. Using the API from core on the hand is blazing fast. I thought it was a core issue, where the script would take too long to decrypt the data, but it's just how the data is been parsed and rendered.

I would love to help out with this if possible.

**Comment by perry-mitchell** [comment]
Hi @neojp - Thanks a lot!

It definitely sounds like we're pushing the limits of the UI - it makes heavy use of React with complex state so it's bound to be a hot mess with such a large number of entries. I think it's definitely a good idea to try and optimise this.

We are, in fact, preparing to release a new UI for the desktop altogether. It's based on a simpler concept and will mean less work when porting it cross platform. We'll pay extra attention to the performance.

We'll be importing from https://github.com/buttercup/ui soon enough to use the new UI, and it'll be released as a new major with a beta soon. I'll leave this issue here so we can monitor the performance of our new release.

**Comment by perry-mitchell** [comment]
We've prepared a new UI which is now available in 2.0. I'll close this issue as it's quite stale, but happy to reopen it if this is still a problem.
