### ISSUE TITLE
Render and edit multiple lines on property values

### ISSUE THREAD

**Issue by neojp** [buttercup/buttercup-desktop#782]
## Backstory
Working on imported data from 1P, I have come across a lot of entries that have notes as a property with multiple lines.

Using core I can confirm that the data is correctly saved as multiple lines using `\r\n`, copying the value on the Desktop UI gives me the correct value.

## Problem
The only problems I've found are:

1. **Fields render content in a single line**
This could be potentially fixed by replacing `\r\n` to `<br>`

2. **Ability to enter multiple lines when editing a field**
You could switch from an `<input>` to a `<textarea>`, style it as a single line field and then resize the field if a user ever presses `shift + enter` to insert another line.

**Comment by perry-mitchell** [comment]
This will soon be handled as we're adding configurable value types - as mentioned in your other issue - via https://github.com/buttercup/ui. Once we utilise the Vault UI from that we'll have the option to change value types so that they can render correctly. 

This will be handled by #742, so I'll close in favour of that. Thanks!
