### ISSUE TITLE
Failed unlocking source

### ISSUE THREAD

**Issue by CriPstian** [buttercup/buttercup-desktop#792]
Having multiple archives synced on Dropbox but only two out of three work when I enter the password.
The issue may not be the Dropbox part, but actually the content of the archieve.
Here is a print screen of the error:
![buttercup-failed-unlocking-source](https://user-images.githubusercontent.com/10658360/61772270-823d5e80-adfa-11e9-8995-6394edb80cd6.png)
In the console there are no errors or warnings.
Please let me know if I can provide more information on this matter.
Thanks!

**Comment by perry-mitchell** [comment]
What version of the desktop application are you using? It sounds as though it’s either out of date, or the file is corrupt. I can’t of course ask you to post the contents of your vault file, but I’d need to see it to know. If it’s just for testing you could share it but otherwise definitely don’t send any part of it here. I’ll try to link instructions on how the file is built shortly so you could debug the contents yourself.

**Comment by CriPstian** [comment]
The current version installed on my computer is `v1.6`, and clicking the `Check for updates` menu button does not trigger anything.
I forgot to specify I am using `Ubuntu 18.04.2 LTS`

**Comment by perry-mitchell** [comment]
Ah I see, that version is indeed out of date. You’ll need to manually install the latest which is 1.16.2, I’m afraid. There was a bug earlier that prevented update notifications.

**Comment by CriPstian** [comment]
I'll do that, and get back to you

**Comment by CriPstian** [comment]
@perry-mitchell That worked, I reinstalled and it went smoothly. Thanks for the suggestion.

**Comment by perry-mitchell** [comment]
Good to hear! Sorry for the inconvenience.
