### ISSUE TITLE
Why save history instead of existing data?

### ISSUE THREAD

**Issue by VARed** [buttercup/buttercup-desktop#827]
After I empty my account and password, I find that the size of .bcup file is larger than before.Why save the history instead of existing data? Saving the history in the PC will make the file larger and larger. What are the benefits of saving the history?

**Comment by perry-mitchell** [comment]
Hi @VARed! Good question.

We have history because passwords are super important. If we only stored a single copy of your credentials for an account, what happens if your password fails when updating it, or something happens remotely that said service needs to roll back their database to an earlier time when your password was in another form?

Basically what we're saying is history is terribly important. Each entry needs history so that you can, at some point when required, look at the previous values in case you need them. Perhaps you mistakenly delete an entry? Or decide to restore an old account and need that old login? Well history can help there.

Currently we don't have any way to view the history in the UI, but this will change soon.

To your point regarding the file size - we're talking about bytes and kilobytes here, which we've made the decision is an acceptable range with which to allow vault growth. Our applications are in the 10s/100s of megabytes so the vault file size is truly insignificant in comparison.

**Comment by perry-mitchell** [comment]
Another reason history is important - users currently save their vaults on cloud storage providers, but will usually have more than 1 device connected to the same storage at once. What happens if a user saves the same vault on one machine but then saves it again on another, so that buttercup has to resolve a conflict? The history also allows for conflict resolution so that no values are lost.

**Comment by VARed** [comment]
@ perry-mitchell OK, I know what you mean. Thank you for your reply.
