### ISSUE TITLE
Multiple instances after launching executable

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#849]
![image](https://user-images.githubusercontent.com/3869469/69012125-f5a34700-097a-11ea-819d-0af8893b676e.png)

It seems as though Buttercup no longer recognises running instances and continues to open new instances. This is obviously non-ideal, and should be fixed. Opening the executable should simply focus a running executable, if one exists.

**Comment by Fl3eK** [comment]
Seem to be the case on linux too, Fedora 31 64bits, WEBDav vault :

`
2019-12-17 09:12:20 > ps aux | grep -i buttercup
ismael     84904  1.1  1.1 810268 139880 ?       Sl   09:12   0:01 /opt/Buttercup/buttercup-desktop
ismael     84909  0.0  0.3 397788 42184 ?        S    09:12   0:00 /opt/Buttercup/buttercup-desktop --type=zygote
ismael     84911  0.0  0.0 397788  7116 ?        S    09:12   0:00 /opt/Buttercup/buttercup-desktop --type=zygote
ismael     84947  0.4  0.9 593536 116772 ?       Sl   09:12   0:00 /opt/Buttercup/buttercup-desktop --type=gpu-process --field-trial-handle=11740841721004548712,2302161362638283836,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=18131242427829036201
ismael     84948  0.1  0.5 466052 64888 ?        Sl   09:12   0:00 /opt/Buttercup/buttercup-desktop --type=utility --field-trial-handle=11740841721004548712,2302161362638283836,131072 --disable-features=SpareRendererForSitePerProcess --lang=fr --service-sandbox-type=network --service-request-channel-token=7907787048649253802 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
ismael     84961  2.6  1.1 737328 139420 ?       Sl   09:12   0:02 /opt/Buttercup/buttercup-desktop --type=renderer --field-trial-handle=11740841721004548712,2302161362638283836,131072 --disable-features=SpareRendererForSitePerProcess --lang=fr --app-path=/opt/Buttercup/resources/app.asar --node-integration --no-sandbox --no-zygote --background-color=#fff --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=5775566595537993349 --renderer-client-id=5 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
`
The result is I can't add new entry (promise error certainly due to multiple process, getting a 503 on the vault file) and can only load one vault at time (weird error on submitting password). 
When I need to unlock an other vault or the same after it was locked, I must kill all processes and restart.

**Comment by perry-mitchell** [comment]
Stale
