### ISSUE TITLE
Disable updates on unsupported Linux builds

### ISSUE THREAD

**Issue by nickbe** [buttercup/buttercup-desktop#917]
The windows update which is following message is not working. There's always one of several error messages.

**Comment by apelly** [comment]
Just installed buttercup-desktop_1.19.0_amd64.deb and:
![image](https://user-images.githubusercontent.com/1776123/84723709-5448a600-afda-11ea-8bae-29d178d4934d.png)

Also, the copy error button? She does nuuuthing!

**Comment by nickbe** [comment]
Exactly. I've never had a normal update process except when running the installer by hand.

**Comment by perry-mitchell** [comment]
Auto-Update is not available on any linux build except for AppImage. All others are not possible to automatically update via Electron's internal update system.

Due to that, we'll be attempting to disable automatic updates on the other builds, like deb/rpm/snap etc.. Sorry for the inconvenience here, I see this issue daily on my Ubuntu install.

**Comment by perry-mitchell** [comment]
Stale
