### ISSUE TITLE
.bcup export is unencrypted 

### ISSUE THREAD

**Issue by nickkostov** [buttercup/buttercup-desktop#971]
Hello there, 
I just did an export of one of my password files and sent it over Slack. 
Slack read the whole file and you can clearly see the the files, could you please elaborate?

**Comment by perry-mitchell** [comment]
When you export vaults from password managers, they're more-often-than-not **unencrypted** because you exported them from their native format. Exporting to an encrypted file isn't super useful if you're trying to import them somewhere else using a generic format. We could certainly add support for encrypted exports but we'd need someone to contribute a common encryption standard for exported vaults.

This is entirely intentional, more or less.

**Comment by perry-mitchell** [comment]
Regarding slack: It is your responsibility to ensure you know that you're transferring - this has nothing to do with Buttercup.
